Vagrant.configure("2") do |config|
	config.vm.define "mradwanS" do |server|
		server.vm.box = "debian/bullseye64"
		server.vm.hostname = "mradwanS"
		server.vm.network "private_network", ip: "192.168.56.110"
		server.vm.provider "virtualbox" do |vb|
			vb.name = "mradwanS"
			vb.memory = "512"
			vb.cpus = 1
		end
		server.vm.provision "shell", inline: <<-SHELL
			apt-get update -y
			apt-get upgrade -y
			apt-get install -y curl
			curl sfL https://get.k3s.io | sh -
		SHELL
	end


	